---
- name: Upgrade all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Install packages firebird
  ansible.builtin.yum:
    name: 
      - firebird
    state: latest

- name: Configure firebird db
  ansible.builtin.shell: echo -e "create user SYSDBA password "'""{{ password_db }}"'"";\nquit;" | isql-fb security.db -user SYSDBA -password masterkey

- name: Restart services
  ansible.builtin.service:
    name: 
      - firebird-superserver 
    state: restarted
    enabled: yes

- name: mkdir /db
  ansible.builtin.file:
    path: /db
    state: directory
    owner: firebird
    group: firebird
    mode: '0774'

- name: sql.sh copy
  ansible.builtin.copy:
    src: sql.sh
    dest: /opt/sql.sh
    owner: root
    group: root
    mode: '0774'

- name: sql.sh exec
  ansible.builtin.shell: /bin/bash /opt/sql.sh

