set sql dialect 3;
create database '/db/redadm.fdb' page_size 16384;
commit;
connect '/db/redadm.fdb';
commit;
create user redadm password 'redadm' grant admin role;
commit;
grant all database to redadm;
grant all table to redadm;
grant all view to redadm;
grant all procedure to redadm;
grant all function to redadm;
grant all package to redadm;
grant all generator to redadm;
grant all sequence to redadm;
grant all domain to redadm;
grant all exception to redadm;
grant all role to redadm;
grant all character set to redadm;
grant all collation to redadm;
grant all filter to redadm;
commit;
quit;
