---
- name: Install postgres
  ansible.builtin.apt:
    name: postgresql-11
    state: present

- name: Create user
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    db: postgres
    name: rupost
    password: {{ db_password }}
    state: present
    expires: infinity
    priv: ALL

- name: Create database rupost
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    community.postgresql.postgresql_db:
    name: rupost
    owner: rupost
    encoding: UTF-8

- name: Create database rupost_data
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    community.postgresql.postgresql_db:
    name: rupost_data
    owner: rupost
    encoding: UTF-8

- name: Create database rupost_logs
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    community.postgresql.postgresql_db:
    name: rupost_logs
    owner: rupost
    encoding: UTF-8

- name: Generate template postgresql
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/11/main/postgresql.conf
  notify:
    - restart postgresql
