---
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname_dc }}"
    use: systemd

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Setenforce 0
  ansible.builtin.shell: setenforce 0

- name: Generate network config
  ansible.builtin.template:
    src: enp1s0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-enp1s0
  when:
    ansible_os_family == "REDOS"
  notify:
    - restart network

- name: Generate resolv config
  ansible.builtin.template:
    src: resolv.j2
    dest: /etc/resolv.conf

- name: Upgrade all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Install packages
  ansible.builtin.yum:
    name: 
      - bind
      - krb5-workstation 
      - /opt/reddc.rpm
    state: latest

- name: Generate /etc/krb5.conf
  ansible.builtin.template:
    src: krb5.j2
    dest: /etc/krb5.conf

- name: Change file ownership, group and permissions /etc/krb5.conf
  ansible.builtin.file:
    path: /etc/krb5.conf
    owner: root
    group: named
    mode: '0644'

- name: copy file /etc/krb5.conf.d/crypto-policies
  ansible.builtin.copy:
    src: crypto-policies
    dest: /etc/krb5.conf.d/crypto-policies



...