---

- name: Install Rupost Node
  ansible.builtin.shell: sh rupost*.sh --silent  --db-host {{ db_ip }} --db-port 5432 --db-user rupost --db-password {{ db_password }} --db-name rupost --data-db-name rupost_data --logs-db-name rupost_logs

- name: Generate openssl dhparam
  ansible.builtin.shell: openssl dhparam -out /opt/rupost-builtin-dhparam.pem 4096

- name: add openssl dhparam
  ansible.builtin.shell: rupost dhparam import /opt/rupost-builtin-dhparam.pem

