---

- name: Install chrony package on Debian based OS
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu" or ansible_facts['os_family'] == "Astra Linux"
  ansible.builtin.apt:
    name: chrony
    state: latest

- name: Disable ntp
  ansible.builtin.service:
    name: ntp
    enabled: notify
    state: stopped

- name: Set chrony config
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
  notify:
    - restart chrony
